using Auth.Application.Exceptions;
using Auth.Application.Helpers;
using Auth.Application.Models;
using Auth.Application.Options;
using Auth.Domain.UserAggregste;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace Auth.Application.UserManagment
{
    public class UserManager
    {
        private readonly IUserRepository _userRepository;
        private readonly IOptions<AuthOptions> _authOptions;
        private readonly PasswordHasher _passwordHasher;
        private readonly TokenRefresher _tokenRefresher;
        private readonly RefreshTokenValidator _refreshTokenValidator;

        public UserManager(IUserRepository userRepository,
                            IOptions<AuthOptions> authOptions,
                            PasswordHasher passwordHasher,
                            TokenRefresher tokenRefresher,
                            RefreshTokenValidator refreshTokenValidator)
        {
            _userRepository = userRepository;
            _authOptions = authOptions;
            _passwordHasher = passwordHasher;
            _tokenRefresher = tokenRefresher;
            _refreshTokenValidator = refreshTokenValidator;
        }

        private User Authentificate(string email, string password)
        {
            var user = _userRepository.GetByEmail(email);

            var check = _passwordHasher.Check(user.Password, password);

            if (!check.IsVerified)
            {
                throw new PasswordNotVerifiedException("Invalid password");
            }
            return user;
        }
        private string GenerateJWT(User user)
        {
            var authParams = _authOptions.Value;
            var claims = new List<Claim>()
            {
                new Claim(JwtRegisteredClaimNames.Email, user.Email),
                new Claim(JwtRegisteredClaimNames.Sub, user.Id.ToString())
            };
            foreach (var role in user.Roles)
            {
                claims.Add(new Claim("role", role.Name.ToString()));
            }

            return TokenGenerator.GenerateJWT(
                    authParams.Secret,
                    authParams.Issuer,
                    authParams.Audience,
                    authParams.TokenLifetime,
                    claims);
        }
        public LoginResult LogIn(string email, string password)
        {
            var user = Authentificate(email, password);
            var token = GenerateJWT(user);
            var refreshToken = _tokenRefresher.GenerateJWT();
            user.RefreshToken = refreshToken;
            _userRepository.AddOrUpdate(user);

            return new LoginResult()
            {
                AccessToken = token,
                RefreshToken = refreshToken
            };
        }
        public void LogOut(int userId)
        {
            var user = _userRepository.Get(userId);
            user.RefreshToken = null;
            _userRepository.AddOrUpdate(user);
        }
        public LoginResult RefreshJWT(string refreshToken)
        {
            var user = _userRepository.GetByRefreshToken(refreshToken);
            bool isValidRefreshToken = _refreshTokenValidator.Validate(refreshToken);
            if (!isValidRefreshToken)
            {
                throw new RefreshTokenNotValidException("Refresh token is not valid.");
            }
            var token = GenerateJWT(user);
            var newRefreshToken = _tokenRefresher.GenerateJWT();
            user.RefreshToken = newRefreshToken;
            _userRepository.AddOrUpdate(user);
            return new LoginResult()
            {
                AccessToken = token,
                RefreshToken = newRefreshToken
            };
        }
        public User Register(User user)
        {
            if (user == null)
            {
                throw new ArgumentNullException("User object can not be null");
            }
            if(string.IsNullOrEmpty(user.Email) || string.IsNullOrEmpty(user.UserName) || string.IsNullOrEmpty(user.Password))
            {
                throw new ArgumentException("user.Email, user.Password and user.UserName is required fields for user object");
            }
            if(user.Id > 0)
            {
                throw new ArgumentException("user.Id is Autogenerated field.");
            }

            var serchedUsers = _userRepository.Get().Where(_user => _user.Email == user.Email || _user.UserName == user.UserName)?.ToList();
            
            if(serchedUsers != null && serchedUsers.Count > 0)
            {
                throw new UserRegisterException($"User with email:'{user.Email}' or with UserName:'{user.UserName}' already exist.");
            }

            user.Password = _passwordHasher.Hash(user.Password);
            var registeredUser = _userRepository.AddOrUpdate(user);
            return registeredUser;
        }
        public void Delete(User user)
        {
            if (user == null || user.Id < 1 || string.IsNullOrEmpty(user.Email) || string.IsNullOrEmpty(user.UserName))
            {
                return;
            }
            _userRepository.Delete(user);
        }
        public string GenerateForgotPasswordToken()
        {
            throw new NotImplementedException();
        }
        public string GenerateEmailVerificationToken()
        {
            throw new NotImplementedException();
        }
        public void ChangeForgotenPassword()
        {
            throw new NotImplementedException();
        }
        public void VerifyEmail()
        {
            throw new NotImplementedException();
        }
    }
}
