using Auth.Application.Helpers;
using Auth.Application.Helpers.JWT.Auth;
using Auth.Application.Helpers.JWT.EmailVerify;
using Auth.Application.Helpers.JWT.RefreshToken;
using Auth.Application.Helpers.JWT.ResetPassword;
using Auth.Application.Result;
using Auth.Domain.UserAggregste;
using Auth.Infrastructure.Services.Email;
using Auth.Infrastructure.Services.Email.Models;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;

namespace Auth.Application.UserManagment
{
    public class UserManager
    {
        private readonly IUserRepository _userRepository;
        private readonly PasswordHasher _passwordHasher;
        private readonly RefreshTokenHelper _refreshTokenHelper;
        private readonly AuthTokenHelper _authTokenHelper;
        private readonly ResetPasswordTokenHelper _resetPasswordTokenHelper;
        private readonly EmailVerifyTokenHelper _emailVerifyTokenHelper;
        private readonly EmailService _emailService;

        public UserManager(IUserRepository userRepository,
                            PasswordHasher passwordHasher,
                            RefreshTokenHelper refreshTokenHelper,
                            AuthTokenHelper authTokenHelper,
                            ResetPasswordTokenHelper resetPasswordTokenHelper,
                            EmailVerifyTokenHelper emailVerifyTokenHelper,
                            EmailService emailService)
        {
            _userRepository = userRepository;
            _passwordHasher = passwordHasher;
            _refreshTokenHelper = refreshTokenHelper;
            _authTokenHelper = authTokenHelper;
            _resetPasswordTokenHelper = resetPasswordTokenHelper;
            _emailVerifyTokenHelper = emailVerifyTokenHelper;
            _emailService = emailService;
        }

        public AuthentificateResult Authentificate(string email, string password)
        {
            var user = _userRepository.GetByEmail(email);
            if(user == null)
            {
                return new AuthentificateResult(user, new Error($"User with Email:{email} does not exist"));
            }
            var check = _passwordHasher.Check(user.Password, password);

            if (!check.IsVerified)
            {
                return new AuthentificateResult(user, new Error("Invalid Password"));
            }
            return new AuthentificateResult(user);
        }
        public LoginResult LogIn(string email, string password)
        {
            var authResult = Authentificate(email, password);
            if (!authResult.IsValid)
            {
                return new LoginResult("", "", authResult.Error);
            }
            var token = _authTokenHelper.GenerateJWT(authResult.User);
            var refreshToken = _refreshTokenHelper.GenerateJWT(authResult.User);
            authResult.User.RefreshToken = refreshToken;
            _userRepository.AddOrUpdate(authResult.User);

            return new LoginResult(token, refreshToken);
        }
        public LogOutResult LogOut(int userId)
        {
            var user = _userRepository.Get(userId);
            if(user == null)
            {
                return new LogOutResult(new Error("User does not exist to logout."));
            }
            user.RefreshToken = null;
            _userRepository.AddOrUpdate(user);
            return new LogOutResult();
        }
        public LoginResult RefreshJWT(string refreshToken)
        {
            var user = _userRepository.GetByRefreshToken(refreshToken);
            if (user == null)
            {
                return new LoginResult("", "", new Error("Refresh token does not exist."));
            }
            var result = _refreshTokenHelper.Validate(refreshToken);
            if (result == null)
            {
                return new LoginResult("", "", new Error("Invalid refresh token."));
            }
            var token = _authTokenHelper.GenerateJWT(user);
            var newRefreshToken = _refreshTokenHelper.GenerateJWT(user);
            user.RefreshToken = newRefreshToken;
            _userRepository.AddOrUpdate(user);
            return new LoginResult(token, newRefreshToken);
        }
        public RegisterResult Register(User user)
        {
            if (user == null)
            {
                return new RegisterResult(user, "", new Error("Cant register empty user object."));
            }
            if(string.IsNullOrEmpty(user.Email) || string.IsNullOrEmpty(user.UserName) || string.IsNullOrEmpty(user.Password))
            {
                return new RegisterResult(user, "", new Error("Email, UserName, Password is required."));
            }
            if(user.Id > 0)
            {
                return new RegisterResult(user, "", new Error("id is Autogenerated field."));
            }

            var serchedUsers = _userRepository.Get().Where(_user => _user.Email == user.Email || _user.UserName == user.UserName || _user.Id == user.Id)?.ToList();
            
            if(serchedUsers != null && serchedUsers.Count > 0)
            {
                return new RegisterResult(user, "", new Error("User allready exist."));
            }

            user.Password = _passwordHasher.Hash(user.Password);
            var registeredUser = _userRepository.AddOrUpdate(user);

            var emailVerifyTokenResult = GenerateEmailVerificationToken(user);

            if (!emailVerifyTokenResult.IsValid)
            {
                return new RegisterResult(user, "", emailVerifyTokenResult.Error);
            }
                
            return new RegisterResult(registeredUser, emailVerifyTokenResult.EmailVerificationToken);
        }

        public void SendEmailVerifyTokenLink(User user, string Link)
        {
            var email = new SendEmailModel()
            {
                EmailAddressesTo = new List<EmailAddress>()
                {
                    new EmailAddress()
                    {
                        Address = user.Email,
                        Name = user.UserName
                    }
                },
                EmailAddressesFrom = new List<EmailAddress>()
                {
                    new EmailAddress()
                    {
                        Address = "auth@auth.com",
                        Name = "Auth"
                    }
                },
                Subject = "Confirm Email Link",
                Body = $"{Link}"
            };
            _emailService.SendEmail(email);
        }

        public void SendResetPasswordToken(User user, string token)
        {
            var email = new SendEmailModel()
            {
                EmailAddressesTo = new List<EmailAddress>()
                {
                    new EmailAddress()
                    {
                        Address = user.Email,
                        Name = user.UserName
                    }
                },
                EmailAddressesFrom = new List<EmailAddress>()
                {
                    new EmailAddress()
                    {
                        Address = "auth@auth.com",
                        Name = "Auth"
                    }
                },
                Subject = "Reset Password Token",
                Body = $"{token}"
            };
            _emailService.SendEmail(email);
        }

        public DeleteUserResult DeleteUser(int userID)
        {
            var user = _userRepository.Get(userID);

            if (user == null || user.Id < 1)
            {
                return new DeleteUserResult(new Error("User is not found to delete."));
            }
            var deleteResult = _userRepository.Delete(user);
            if (!deleteResult)
            {
                return new DeleteUserResult(new Error("user is not exist."));
            }
            return new DeleteUserResult();
        }
        public GenerateResetPasswordTokenResult GenerateResetPasswordToken(string userEmail)
        {
            var user = _userRepository.GetByEmail(userEmail);
            if(user == null || user.Id < 1)
            {
                return new GenerateResetPasswordTokenResult("", user, new Error("user is not valid or not exist."));
            }
            var token = _resetPasswordTokenHelper.GenerateJWT(user);
            if (string.IsNullOrEmpty(token))
            {
                return new GenerateResetPasswordTokenResult("", user, new Error("reset password token generating failed."));
            }
            return new GenerateResetPasswordTokenResult(token, user);
        }
        public GenerateEmailVerificationTokenResult GenerateEmailVerificationToken(User user)
        {
            if (user == null || user.Id < 1)
            {
                return new GenerateEmailVerificationTokenResult("", new Error("user is not valid"));
            }
            var token = _emailVerifyTokenHelper.GenerateJWT(user);
            return new GenerateEmailVerificationTokenResult(token);
        }
        public ResetPasswordResult ResetPassword(string token, string password)
        {
            var result = _resetPasswordTokenHelper.Validate(token);
            if (result == null)
            {
                return new ResetPasswordResult(new Error("Invalid token."));
            }
            var UserIdClaim = result.Claims.FirstOrDefault(c => c.Type == JwtRegisteredClaimNames.Sub);
            if(UserIdClaim == null)
            {
                return new ResetPasswordResult(new Error("User is not present in token."));
            }
            if (Int32.TryParse(UserIdClaim.Value, out int UserID) && UserID != 0)
            {
                var user = _userRepository.Get(UserID);
                if (user == null)
                {
                    return new ResetPasswordResult(new Error("Reset password failed. User does not exist."));
                }
                user.Password = _passwordHasher.Hash(password);
                _userRepository.AddOrUpdate(user);
                return new ResetPasswordResult();
            }
            return new ResetPasswordResult(new Error("Reset password failed. Invalid User.Id"));
        }
        public VerifyEmailResult VerifyEmail(string token)
        {
            var result = _emailVerifyTokenHelper.Validate(token);
            if(result == null)
            {
                return new VerifyEmailResult(new Error("Invalid token."));
            }
            var UserIdClaim = result.Claims.FirstOrDefault(c => c.Type == JwtRegisteredClaimNames.Sub);
            if (UserIdClaim == null)
            {
                return new VerifyEmailResult(new Error("User is not present in token."));
            }
            if (Int32.TryParse(UserIdClaim.Value, out int UserID) && UserID != 0)
            {
                var user = _userRepository.Get(UserID);
                if(user == null)
                {
                    return new VerifyEmailResult(new Error("Email verification failed. User does not exist."));
                }
                if (user.IsVerified)
                {
                    return new VerifyEmailResult(new Error("User allready Verified"));
                }
                 user.IsVerified = true;
                 _userRepository.AddOrUpdate(user);
                return new VerifyEmailResult();
            }
            return new VerifyEmailResult(new Error("Email verification failed. Invalid User.Id"));
        }
    }
}
